# Given two strings ss and tt, tt is a substring of ss if tt is contained as a contiguous collection of symbols in ss (as a result, tt must be no longer than ss).
substring_index <- function(string,pattern){
  l = nchar(pattern)
  string2 = unlist(strsplit(string,""))
  if(l>length(string2))
  {
    print("pattern cant be longer than string")
  }
  else
  {
    matched_locations=c()
    for(i in seq_along(string2))
    {
      if( paste(string2[i:(i+l-1)],collapse="") == pattern )
      {
        matched_locations = c(matched_locations,i)
      }
    }
    return(matched_locations)
  }
}

dna = "GATATATGCATATACTT"
motif = "ATAT"
substring_index(dna,motif)

dna2 = "ATCCAACGTAGGAACGTAGAACGTAGCAAACGTAGTAAACGTAGGAACGTAGACAACGTAGCAACGTAGAGATACATAACGTAGAACGTAGAACGTAGAACGTAGAACGTAGCTGAACGTAGAAAAACGTAGTTAAACGTAGAACGTAGGGAACGTAGAACGTAGTGAAACCTCCGTTGCTTAGAAACGTAGAAACGTAGTGGCCGTAACGACTTAAACGTAGACTCTCAACGTAGGTCTAACGTAGAACGTAGTAACGTAGGTAACGTAGTGAACGTAGGGCCGGCCAACGTAGAAACGTAGGCACATCAAACGTAGAGCTGAACGTAGGATTATAACGTAGAACGTAGACGAACGTAGGGATAACGTAGTAAGCAGAACGTAGTAGAGGAACGTAGAACGTAGACGTTGTTAACGTAGGGCCTTCAACGTAGCGAGGTAACGTAGCCAACGTAGAAACGTAGCCAAACGTAGAAAACGTAGGGGCCCCGTAAACGTAGCTCAACGTAGAAACGTAGAACGTAGAAACGTAGGAACGTAGAACGTAGAACGTAGGAACGTAGAACGTAGAACGTAGAACGTAGTTACCGGAAACGTAGACACACCAACGTAGCCAACGTAGAGACAACGTAGCTCTTAAACGTAGAACGTAGCTAGCAACGTAGGGACAACGTAGAACGTAGCAACGTAGTAACGTAGCAACGTAGAACGTAGGCGAACGTAGAACGTAGGAACGTAGTTGAACGTAGGCAACGTAGGGCGAACGTAGTCAACGTAGCCCAAACGTAGAACGTAGATGACAACGTAGTAACGTAGGGTGAACGTAGCCAACGTAGAACGTAGGTAAACGTAGAACGTAG"
motif2 = "AACGTAGAA"
substring_index(dna2,motif2)
  

